-- Copyright (c) 2026 Scott Armstrong and Vlad Vicol.
-- Released under Apache 2.0 license.

module

public import AVenhance.Statements.Construction.BarNorm
public import AVenhance.Statements.Construction.ExistsIsStreamSeq
public import AVenhance.Statements.Construction.IsAdmissibleStream
public import AVenhance.Statements.Construction.IsStreamSeqAdmPred
public import AVenhance.Statements.Construction.IsStreamSeq
public import AVenhance.Statements.Construction.IsStreamSeqUnique
public import AVenhance.Statements.Construction.LimitFieldRegular
public import AVenhance.Statements.Construction.NextStreamAdmissible
public import AVenhance.Statements.Construction.NextStream
public import AVenhance.Statements.Construction.NextStreamSummable
public import AVenhance.Statements.Construction.NextStreamTerm
public import AVenhance.Statements.Construction.StreamRegularity
public import AVenhance.Statements.Construction.StreamVelContinuous
public import AVenhance.Statements.Construction.StreamVel
public import AVenhance.Statements.Construction.StreamVelLipschitz
public import AVenhance.Statements.FlowDefs.FlowInv
public import AVenhance.Statements.FlowDefs.FlowInvLeftInverse
public import AVenhance.Statements.FlowDefs.FlowInvRightInverse
public import AVenhance.Statements.FlowDefs.FlowIsFlow
public import AVenhance.Statements.FlowDefs.Flow
public import AVenhance.Statements.FlowDefs.FlowUnique
public import AVenhance.Statements.Flow.ExistsUniqueFlow
public import AVenhance.Statements.Flow.IsFlow
public import AVenhance.Statements.FullTheorem.AnomalousDissipationFull
public import AVenhance.Statements.FullTheorem.HolderTimeL2Le
public import AVenhance.Statements.FullTheorem.IsHolderTimeL2
public import AVenhance.Statements.FullTheorem.IsTransportWeakSolution
public import AVenhance.Statements.FullTheorem.LebronStep
public import AVenhance.Statements.Ingredients.A
public import AVenhance.Statements.Ingredients.Delta
public import AVenhance.Statements.Ingredients.Epsilon
public import AVenhance.Statements.Ingredients.Gamma
public import AVenhance.Statements.Ingredients.HatXiML
public import AVenhance.Statements.Ingredients.HatZetaML
public import AVenhance.Statements.Ingredients.IndIcc
public import AVenhance.Statements.Ingredients.Ingredients
public import AVenhance.Statements.Ingredients.LIdx
public import AVenhance.Statements.Ingredients.Nonempty
public import AVenhance.Statements.Ingredients.Nstar
public import AVenhance.Statements.Ingredients.Psi0
public import AVenhance.Statements.Ingredients.Psi
public import AVenhance.Statements.Ingredients.Q
public import AVenhance.Statements.Ingredients.ScaledCutoff
public import AVenhance.Statements.Ingredients.ShiftCutoff
public import AVenhance.Statements.Ingredients.Tau
public import AVenhance.Statements.Ingredients.TauP
public import AVenhance.Statements.Ingredients.TauPP
public import AVenhance.Statements.Ingredients.XiMK
public import AVenhance.Statements.Ingredients.ZetaMK
public import AVenhance.Statements.Roots.AnomalousDissipation
public import AVenhance.Statements.Roots.GradNormSq
public import AVenhance.Statements.Roots.IsContinuousIntoHolder
public import AVenhance.Statements.Roots.IsDivFree
public import AVenhance.Statements.Roots.IsHolderClass
public import AVenhance.Statements.Roots.IsPeriodicH1
public import AVenhance.Statements.Roots.IsPeriodicH1WithExistsH1Function
public import AVenhance.Statements.Roots.IsPeriodicH1With
public import AVenhance.Statements.Roots.IsTestFunction
public import AVenhance.Statements.Roots.IsWeakSolutionGrad
public import AVenhance.Statements.Roots.IsWeakSolution
public import AVenhance.Statements.Roots.IsZ2Periodic
public import AVenhance.Statements.Roots.L2NormSq
public import AVenhance.Statements.Roots.LatticeShift
public import AVenhance.Statements.Roots.SpaceGrad
public import AVenhance.Statements.Roots.SpaceTimeGradNormSq
public import AVenhance.Statements.Roots.TimeCube
public import AVenhance.Statements.Roots.UnitCube
public import AVenhance.Statements.Roots.WeakWellposed
public import AVenhance.Statements.Section3.ChiMKIsUniqueSolution
public import AVenhance.Statements.Section3.ChiMK
public import AVenhance.Statements.Section3.ChiM
public import AVenhance.Statements.Section3.CorrTime
public import AVenhance.Statements.Section3.FluxIntegrand
public import AVenhance.Statements.Section3.Flux
public import AVenhance.Statements.Section3.GradMatrix
public import AVenhance.Statements.Section3.IsCorrectorSol
public import AVenhance.Statements.Section3.JHat
public import AVenhance.Statements.Section3.JMN
public import AVenhance.Statements.Section3.KappaAt
public import AVenhance.Statements.Section3.KhomEqScalar
public import AVenhance.Statements.Section3.Khom
public import AVenhance.Statements.Section3.KhomScalar
public import AVenhance.Statements.Section3.KMat
public import AVenhance.Statements.Section3.LMN
public import AVenhance.Statements.Section3.LRecurse
public import AVenhance.Statements.Section3.PermissibleSet
public import AVenhance.Statements.Section3.PermittedInterval
public import AVenhance.Statements.Section3.PsiM
public import AVenhance.Statements.Section3.QMNRChar
public import AVenhance.Statements.Section3.QMNR
public import AVenhance.Statements.Section3.SigmaMat
public import AVenhance.Statements.Section3.SpaceAvg
public import AVenhance.Statements.Section3.SpaceAvgMat
public import AVenhance.Statements.Section3.SpaceLap
public import AVenhance.Statements.Section3.TimeAvgMat
public import AVenhance.Statements.Section3.UShear
public import AVenhance.Statements.Section3.ZetaProd
public import AVenhance.Statements.Section4.AdvDiffOp
public import AVenhance.Statements.Section4.Amnr
public import AVenhance.Statements.Section4.Ansatz
public import AVenhance.Statements.Section4.BigBound
public import AVenhance.Statements.Section4.ChiTilde
public import AVenhance.Statements.Section4.ClassicalWellposed
public import AVenhance.Statements.Section4.FlowGrad
public import AVenhance.Statements.Section4.HMinusOneNorm
public import AVenhance.Statements.Section4.Hm
public import AVenhance.Statements.Section4.Hmr
public import AVenhance.Statements.Section4.IndyStepDown
public import AVenhance.Statements.Section4.IsClassicalSol
public import AVenhance.Statements.Section4.IsThetaAnalytic
public import AVenhance.Statements.Section4.IsTIterates
public import AVenhance.Statements.Section4.Jcut
public import AVenhance.Statements.Section4.KappaSeq
public import AVenhance.Statements.Section4.KappaSeqPred
public import AVenhance.Statements.Section4.MTheta0IsLeast
public import AVenhance.Statements.Section4.MTheta0
public import AVenhance.Statements.Section4.SMat
public import AVenhance.Statements.Section4.TForcing
public import AVenhance.Statements.Section4.VecDiv
public import AVenhance.Statements.Section4.XFlowInv
public import AVenhance.Statements.Section4.XFlow

/-! All public statements of the formalization: one declaration per imported file. -/
