-- Copyright (c) 2026 Scott Armstrong and Vlad Vicol.
-- Released under Apache 2.0 license.

module

public import AVenhance.Infra.Cutoff.SmoothStep

/-! Locally finite partitions generated by complementary smooth steps. -/

@[expose] public section

noncomputable section

namespace AVenhance.Infra.Cutoff

/-- A one-dimensional cutoff around the center of a lattice cell. `margin` is the
distance from the cell edge to the edge of the support. -/
def cellCutoff (s : ℝ → ℝ) (period margin x : ℝ) : ℝ :=
  s ((x + period / 2 + margin) / (2 * margin)) *
    s ((period / 2 + margin - x) / (2 * margin))

theorem cellCutoff_even (s : ℝ → ℝ) (period margin x : ℝ) :
    cellCutoff s period margin (-x) = cellCutoff s period margin x := by
  unfold cellCutoff
  have h₁ : (-x + period / 2 + margin) / (2 * margin) =
      (period / 2 + margin - x) / (2 * margin) := by ring
  have h₂ : (period / 2 + margin - -x) / (2 * margin) =
      (x + period / 2 + margin) / (2 * margin) := by ring
  rw [h₁, h₂, mul_comm]

theorem cellCutoff_zero_of_le {s : ℝ → ℝ} {period margin x : ℝ}
    (hm : 0 < margin) (hs : ∀ y, y ≤ 0 → s y = 0)
    (hx : x ≤ -(period / 2 + margin)) : cellCutoff s period margin x = 0 := by
  unfold cellCutoff
  have harg : (x + period / 2 + margin) / (2 * margin) ≤ 0 := by
    rw [div_le_iff₀ (by positivity : 0 < 2 * margin)]
    linarith
  rw [hs _ harg, zero_mul]

theorem cellCutoff_zero_of_ge {s : ℝ → ℝ} {period margin x : ℝ}
    (hm : 0 < margin) (hs : ∀ y, y ≤ 0 → s y = 0)
    (hx : period / 2 + margin ≤ x) : cellCutoff s period margin x = 0 := by
  unfold cellCutoff
  have harg : (period / 2 + margin - x) / (2 * margin) ≤ 0 := by
    rw [div_le_iff₀ (by positivity : 0 < 2 * margin)]
    linarith
  rw [hs _ harg, mul_zero]

theorem cellCutoff_one_on_core {s : ℝ → ℝ} {period margin x : ℝ}
    (hm : 0 < margin) (hs : ∀ y, 1 ≤ y → s y = 1)
    (hx₁ : -period / 2 + margin ≤ x) (hx₂ : x ≤ period / 2 - margin) :
    cellCutoff s period margin x = 1 := by
  unfold cellCutoff
  have harg₁ : 1 ≤ (x + period / 2 + margin) / (2 * margin) := by
    rw [le_div_iff₀ (by positivity : 0 < 2 * margin)]
    linarith
  have harg₂ : 1 ≤ (period / 2 + margin - x) / (2 * margin) := by
    rw [le_div_iff₀ (by positivity : 0 < 2 * margin)]
    linarith
  rw [hs _ harg₁, hs _ harg₂]
  norm_num

theorem cellCutoff_pair_right {s : ℝ → ℝ} {period margin x : ℝ}
    (hm : 0 < margin) (hs₁ : ∀ y, 1 ≤ y → s y = 1)
    (hs₂ : ∀ y, s (1 - y) = 1 - s y)
    (hpm : 2 * margin ≤ period)
    (hx₁ : period / 2 - margin ≤ x) (hx₂ : x ≤ period / 2) :
    cellCutoff s period margin x +
      cellCutoff s period margin (x - period) = 1 := by
  have hleft : 1 ≤ (x + period / 2 + margin) / (2 * margin) := by
    rw [le_div_iff₀ (by positivity : 0 < 2 * margin)]
    nlinarith [hpm]
  have hright : 1 ≤ (period / 2 + margin - (x - period)) / (2 * margin) := by
    rw [le_div_iff₀ (by positivity : 0 < 2 * margin)]
    nlinarith [hpm]
  have hsmall :
      (x - period + period / 2 + margin) / (2 * margin) =
        1 - (period / 2 + margin - x) / (2 * margin) := by
    field_simp
    ring
  unfold cellCutoff
  rw [hs₁ _ hleft, hs₁ _ hright, hsmall, hs₂]
  ring

theorem cellCutoff_pair_left {s : ℝ → ℝ} {period margin x : ℝ}
    (hm : 0 < margin) (hs₁ : ∀ y, 1 ≤ y → s y = 1)
    (hs₂ : ∀ y, s (1 - y) = 1 - s y)
    (hpm : 2 * margin ≤ period)
    (hx₁ : -period / 2 ≤ x) (hx₂ : x ≤ -period / 2 + margin) :
    cellCutoff s period margin x +
      cellCutoff s period margin (x + period) = 1 := by
  have h := cellCutoff_pair_right (s := s) (period := period) (margin := margin)
    (x := -x) hm hs₁ hs₂ hpm (by linarith) (by linarith)
  rw [cellCutoff_even] at h
  have heven : cellCutoff s period margin (-x - period) =
      cellCutoff s period margin (x + period) := by
    rw [show -x - period = -(x + period) by ring, cellCutoff_even]
  rw [heven] at h
  simpa [cellCutoff_even] using h

theorem cellCutoff_lattice_partition {s : ℝ → ℝ} {period margin t : ℝ}
    (hperiod : 0 < period) (hmargin : 0 < margin) (hmargin' : 2 * margin ≤ period)
    (hzero : ∀ y, y ≤ 0 → s y = 0) (hone : ∀ y, 1 ≤ y → s y = 1)
    (hcomp : ∀ y, s (1 - y) = 1 - s y) :
    ∑' k : ℤ, cellCutoff s period margin
      (t - (k : ℝ) * period) = 1 := by
  let n : ℤ := Int.floor ((t + period / 2) / period)
  let u : ℝ := t - (n : ℝ) * period
  have hnlo : (n : ℝ) ≤ (t + period / 2) / period := by
    dsimp [n]
    exact Int.floor_le _
  have hnhi : (t + period / 2) / period < (n : ℝ) + 1 := by
    dsimp [n]
    exact Int.lt_floor_add_one _
  have hu_lo : -period / 2 ≤ u := by
    dsimp [u]
    rw [le_div_iff₀ hperiod] at hnlo
    linarith
  have hu_hi : u ≤ period / 2 := by
    dsimp [u]
    rw [div_lt_iff₀ hperiod] at hnhi
    linarith
  have ht : t = u + (n : ℝ) * period := by
    dsimp [u]
    ring
  have hshift :
      (∑' k : ℤ, cellCutoff s period margin (t - (k : ℝ) * period)) =
        ∑' k : ℤ, cellCutoff s period margin (u - (k : ℝ) * period) := by
    rw [ht, ← (Equiv.addRight n).tsum_eq]
    simp only [Equiv.coe_addRight, Int.cast_add, add_mul]
    congr 1
    ext k
    ring_nf
  rw [hshift]
  have hfar : ∀ k : ℤ, k ∉ ({-1, 0, 1} : Finset ℤ) →
      cellCutoff s period margin (u - (k : ℝ) * period) = 0 := by
    intro k hk
    have hkcase : k ≤ -2 ∨ 2 ≤ k := by
      have hk' : k ≠ -1 ∧ k ≠ 0 ∧ k ≠ 1 := by simpa using hk
      omega
    rcases hkcase with hkneg | hkpos
    · apply cellCutoff_zero_of_ge hmargin hzero
      have hmP : margin ≤ period := by linarith
      have hmul : (-(k : ℝ)) * period ≥ 2 * period := by
        have : (2 : ℤ) ≤ -k := by omega
        exact mul_le_mul_of_nonneg_right (by exact_mod_cast this) hperiod.le
      dsimp [u] at hu_lo hu_hi ⊢
      nlinarith
    · apply cellCutoff_zero_of_le hmargin hzero
      have hmul : (k : ℝ) * period ≥ 2 * period := by
        exact mul_le_mul_of_nonneg_right (by exact_mod_cast hkpos) hperiod.le
      dsimp [u] at hu_lo hu_hi ⊢
      nlinarith
  have hsumfinite :
      (∑' k : ℤ, cellCutoff s period margin (u - (k : ℝ) * period)) =
        ∑ k ∈ ({-1, 0, 1} : Finset ℤ),
          cellCutoff s period margin (u - (k : ℝ) * period) := by
    exact tsum_eq_sum hfar
  rw [hsumfinite]
  have hshape :
    (∑ k ∈ ({-1, 0, 1} : Finset ℤ),
        cellCutoff s period margin (u - (k : ℝ) * period)) =
        cellCutoff s period margin (u + period) +
          cellCutoff s period margin u + cellCutoff s period margin (u - period) := by
    norm_num [Finset.sum_insert]
    ring
  rw [hshape]
  by_cases huR : u ≤ period / 2 - margin
  · by_cases huL : -period / 2 + margin ≤ u
    · have h0 := cellCutoff_one_on_core hmargin hone huL huR
      have hm : margin ≤ period := by linarith
      have hneg : cellCutoff s period margin (u + period) = 0 := by
        apply cellCutoff_zero_of_ge hmargin hzero
        linarith [huL]
      have hpos : cellCutoff s period margin (u - period) = 0 := by
        apply cellCutoff_zero_of_le hmargin hzero
        linarith [huR]
      rw [hneg, h0, hpos]
      norm_num
    · have huL' : u ≤ -period / 2 + margin := le_of_not_ge huL
      have hpair := cellCutoff_pair_left hmargin hone hcomp hmargin' hu_lo huL'
      have hm : margin ≤ period := by linarith
      have hpos : cellCutoff s period margin (u - period) = 0 := by
        apply cellCutoff_zero_of_le hmargin hzero
        linarith
      rw [hpos, add_zero]
      simpa [add_comm] using hpair
  · have huR' : period / 2 - margin ≤ u := le_of_not_ge huR
    have hpair := cellCutoff_pair_right hmargin hone hcomp hmargin' huR' hu_hi
    have hm : margin ≤ period := by linarith
    have hneg : cellCutoff s period margin (u + period) = 0 := by
      apply cellCutoff_zero_of_ge hmargin hzero
      linarith [huR']
    rw [hneg, zero_add, hpair]

end AVenhance.Infra.Cutoff
