-- Copyright (c) 2026 Scott Armstrong and Vlad Vicol.
-- Released under Apache 2.0 license.

module

public import AVenhance.Infra.Construction.StreamAdmissible
public import AVenhance.Statements.Section4.VecDiv
public import Mathlib.Analysis.Calculus.LineDeriv.IntegrationByParts
public import Mathlib.Analysis.Calculus.FDeriv.Symmetric
public import Mathlib.MeasureTheory.Integral.Bochner.Basic

/-! Classical regularity and incompressibility of the admissible stream velocity. -/

@[expose] public section

noncomputable section

open Homogenization
open MeasureTheory

namespace AVenhance.Infra.Classical

/-- The velocity generated by an admissible stream is smooth and jointly periodic. -/
theorem streamVel_smoothPeriodic (φ : ℝ → Vec 2 → ℝ)
    (hφ : AVenhance.IsAdmissibleStream φ) :
    AVenhance.Infra.Flow.SmoothPeriodicField (AVenhance.streamVel φ) :=
  AVenhance.Infra.Construction.smoothPeriodic_streamVel hφ

/-- Every fixed-order space-time derivative of the admissible stream velocity is globally bounded.
The bound depends on the derivative order. -/
theorem streamVel_global_derivative_bound (φ : ℝ → Vec 2 → ℝ)
    (hφ : AVenhance.IsAdmissibleStream φ) (n : ℕ) :
    ∃ C : ℝ, 0 ≤ C ∧ ∀ p : ℝ × Vec 2,
      ‖iteratedFDeriv ℝ n (Function.uncurry (AVenhance.streamVel φ)) p‖ ≤ C :=
  AVenhance.Infra.Flow.exists_global_iteratedFDeriv_bound
    (streamVel_smoothPeriodic φ hφ) n

theorem Drift.streamVel_mixed_partials_cancel (φ : ℝ → Vec 2 → ℝ)
    (hφ : AVenhance.IsAdmissibleStream φ) (t : ℝ) (x : Vec 2) :
    AVenhance.spaceGrad (fun y => AVenhance.spaceGrad (φ t) y 0) x 1 =
      AVenhance.spaceGrad (fun y => AVenhance.spaceGrad (φ t) y 1) x 0 := by
  let f : Vec 2 → ℝ := φ t
  let g : Vec 2 → Vec 2 →L[ℝ] ℝ := fun y => fderiv ℝ f y
  have hf : ContDiff ℝ (⊤ : ℕ∞) f := by
    exact hφ.1.comp (contDiff_const.prodMk contDiff_id)
  have hg : ContDiff ℝ (⊤ : ℕ∞) g := hf.fderiv_right (by simp)
  have hx : HasFDerivAt g (fderiv ℝ g x) x :=
    ((hg.differentiable (by simp)) x).hasFDerivAt
  have hfirst (y : Vec 2) : HasFDerivAt f (fderiv ℝ f y) y :=
    (hf.differentiable (by simp) y).hasFDerivAt
  have hsym := second_derivative_symmetric hfirst hx
    (Homogenization.basisVec 0) (Homogenization.basisVec 1)
  have hleft : AVenhance.spaceGrad
      (fun y => AVenhance.spaceGrad f y 0) x 1 =
      fderiv ℝ g x (Homogenization.basisVec 1) (Homogenization.basisVec 0) := by
    change fderiv ℝ (fun y => fderiv ℝ f y (Homogenization.basisVec 0)) x
      (Homogenization.basisVec 1) = _
    rw [fderiv_clm_apply (by exact (hg.differentiable (by simp)) x) (by fun_prop)]
    simp [g]
  have hright : AVenhance.spaceGrad
      (fun y => AVenhance.spaceGrad f y 1) x 0 =
      fderiv ℝ g x (Homogenization.basisVec 0) (Homogenization.basisVec 1) := by
    change fderiv ℝ (fun y => fderiv ℝ f y (Homogenization.basisVec 1)) x
      (Homogenization.basisVec 0) = _
    rw [fderiv_clm_apply (by exact (hg.differentiable (by simp)) x) (by fun_prop)]
    simp [g]
  rw [hleft, hright]
  exact hsym.symm

/-- Every spatial slice of an admissible stream velocity has zero classical divergence. -/
theorem streamVel_vecDiv_eq_zero (φ : ℝ → Vec 2 → ℝ)
    (hφ : AVenhance.IsAdmissibleStream φ) (t : ℝ) (x : Vec 2) :
    AVenhance.vecDiv (AVenhance.streamVel φ t) x = 0 := by
  have hv : AVenhance.streamVel φ t = fun y =>
      ![-AVenhance.spaceGrad (φ t) y 1, AVenhance.spaceGrad (φ t) y 0] := by
    funext y
    ext i
    fin_cases i
    · simp [AVenhance.streamVel, AVenhance.sigmaMat, Matrix.mulVec, dotProduct,
        Fin.sum_univ_two, AVenhance.spaceGrad, Homogenization.basisVec]
    · simp [AVenhance.streamVel, AVenhance.sigmaMat, Matrix.mulVec, dotProduct,
        Fin.sum_univ_two, AVenhance.spaceGrad, Homogenization.basisVec]
  change AVenhance.vecDiv (fun y => AVenhance.streamVel φ t y) x = 0
  rw [hv]
  simp only [AVenhance.vecDiv, Fin.sum_univ_two]
  have hcancel := Drift.streamVel_mixed_partials_cancel φ hφ t x
  simp only [Matrix.cons_val_zero, Matrix.cons_val_one, AVenhance.spaceGrad,
    fderiv_fun_neg, neg_apply]
  simp only [AVenhance.spaceGrad] at hcancel
  linarith [hcancel]

end AVenhance.Infra.Classical

end
